#!/bin/sh

uci -q batch <<-EOF >/dev/null
	del ucitrack.@smartinfo[-1]
	add ucitrack smartinfo
	set ucitrack.@smartinfo[-1].init=smartinfo
	commit ucitrack
EOF

# remove LuCI cache
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
